# Stage 1: Build the React app
FROM node:18 AS build

WORKDIR /app

COPY package*.json ./
RUN npm install
COPY . .

RUN npm run build

# Stage 2: Serve the app with Node.js
FROM node:18

WORKDIR /app

# Copy the built React app from the previous stage
COPY --from=build /app/build ./build

# Install dependencies for the server
COPY package*.json ./
RUN npm install

# Command to start the app using npm start
CMD ["npm", "start"]

EXPOSE 3000
